### PR TITLE
use MD5 hashes when available

### LINKED ISSUE #36: unexpected EOF leads to corrupted siva files.
Using
```bash
cat index.csv | grep -oE '[0-9a-f]{40}\.siva' | pga get -i --output /media/k/data/PGA/
```
to download PGA dataset I get `unexpected EOF` just for several files:
```
➜  sourced cat index.csv | grep -oE '[0-9a-f]{40}\.siva' | pga get -i --output /media/k/data/PGA/
downloading siva files by name from stdin
filter flags will be ignored
 67503 / 257391 [====================>--------------------------------------------------------]  26.23% 40m24s
could not get siva/latest/d9/d9363d1f63b2bee2c69c2a11a5f7b0fafc838f0f.siva: could not check mod time in http://pga.sourced.tech//siva/latest/d9/d9363d1f63b2bee2c69c2a11a5f7b0fafc838f0f.siva: Head http://pga.sourced.tech//siva/latest/d9/d9363d1f63b2bee2c69c2a11a5f7b0fafc838f0f.siva: dial tcp 147.135.10.8:80: i/o timeout
 91710 / 257391 [===========================>-------------------------------------------------]  35.63% 44m47s
could not get siva/latest/de/de879ba477d94f28d561b3cd55079a737ec57a85.siva: could not copy http://pga.sourced.tech//siva/latest/de/de879ba477d94f28d561b3cd55079a737ec57a85.siva to /media/k/data/PGA/siva/latest/de/de879ba477d94f28d561b3cd55079a737ec57a85.siva: unexpected EOF
 205637 / 257391 [===========================================================>--------------]  79.89% 2h27m11s
could not get siva/latest/c3/c33c209a937af7468bba45e9406a7e5834655541.siva: could not copy http://pga.sourced.tech//siva/latest/c3/c33c209a937af7468bba45e9406a7e5834655541.siva to /media/k/data/PGA/siva/latest/c3/c33c209a937af7468bba45e9406a7e5834655541.siva: unexpected EOF
 206423 / 257391 [===========================================================>--------------]  80.20% 2h26m33s
could not get siva/latest/f1/f1f0797a2604519e41be05d81e16cad9969145e7.siva: could not copy http://pga.sourced.tech//siva/latest/f1/f1f0797a2604519e41be05d81e16cad9969145e7.siva to /media/k/data/PGA/siva/latest/f1/f1f0797a2604519e41be05d81e16cad9969145e7.siva: unexpected EOF
 257391 / 257391 [========================================================================================================================================================] 100.00%
```
may be due to network problems or something else.
But at the end these files were present. When I manually download them and put to the corresponding folder I found out that the sizes are really different. 
screenshot from 2018-03-16 14-27-59

So, it is better to delete such files or try to redownload it several times.

### LINKED ISSUE #37: check md5 files to decide whether they should be downloaded again
This should fix the problems with interrupted downloads and corrupted files too.

### PR DESCRIPTION
**Pull request by campoy**
Fixes #36 
Fixes #37

Signed-off-by: Francesc Campoy <campoy@golang.org>

### CODE REVIEW

**Comment by bzz** [comment]
Nice improvement @campoy !

I have tried runnning it with the corrupted (partial) and here is an output

```
$ ./pga.v2 list | wc -l

WARN[0000] could not check md5 hashes for latest.csv.gz, comparing timestamps instead: could not fetch hash at latest.csv.gz.md5: 404 Not Found
Error: unexpected EOF
Usage:
  pga list [flags]

Flags:
  -f, --format string      format of the output (url, csv, or json) (default "url")
  -h, --help               help for list
  -l, --lang stringSlice   list of languages that the repositories should have
  -u, --url string         regular expression that repo urls need to match

Global Flags:
  -v, --verbose   log more information

10589
```

I find it a bit confusing, allthough #57 should help, but still may be it can be improved here a bit, instead of printing CLI help in this case together with cryptic `Error: unexpected EOF` ?

Here is FS stat

```
stat ~/.pga/latest.csv.gz
  File: /Users/alex/.pga/latest.csv.gz
  Size: 1573649   	Blocks: 3080       IO Block: 4096   regular file
Device: 1000004h/16777220d	Inode: 23927156    Links: 1
Access: (0644/-rw-r--r--)  Uid: (  501/    alex)   Gid: (   20/   staff)
Access: 2018-05-14 11:35:50.000000000 +0200
Modify: 2018-05-14 11:16:57.000000000 +0200
Change: 2018-05-14 11:16:57.000000000 +0200
Birth: 2018-03-27 07:20:58.000000000 +0200
```

File: PublicGitArchive/pga/cmd/cache.go [hunk 1]
```diff
@@ -16,46 +15,68 @@ const (
...
+}
+
+func upToDate(dest, source FileSystem, name string) bool {
+	ok, err := matchHash(dest, source, name)
+	if err == nil {
+		return ok
+	}
+	logrus.Warnf("could not check md5 hashes for %s, comparing timestamps instead: %v", name, err)
+
+	localTime, err := dest.ModTime(name)
```
Comment (bzz) [inline PublicGitArchive/pga/cmd/cache.go]: Wandering, what is the reason to use `ModTime` in local FS? 

As posted in https://github.com/src-d/datasets/pull/58#issuecomment-388757968 - it seems that modification time is updated on my system for some reason, although the index file is old and corrupted.

File: PublicGitArchive/pga/cmd/cache.go [hunk 2]
```diff
@@ -16,46 +15,68 @@ const (
...
+	if err != nil {
+		logrus.Warnf("could not check mod time in %s: %v", dest.Abs(name), err)
+		return false
+	}
+
+	remoteTime, err := source.ModTime(name)
+	if err != nil {
+		logrus.Warnf("could not check mod time in %s: %v", dest.Abs(name), err)
```
Comment (bzz) [inline PublicGitArchive/pga/cmd/cache.go]: I wonder if on the first `pga get` first-time user experience will be optimal, or these 2 checks would be too noisy?  

As there are no files yet, it will result in `#of-siva-files x 2` warnings printed in CLI and that might not be something expected or obviously-safe-to-ignore for the user.

File: PublicGitArchive/pga/cmd/cache.go [hunk 3]
```diff
@@ -66,11 +87,8 @@ func getIndex() (io.ReadCloser, error) {
 	dest := localFS(filepath.Join(usr.HomeDir, ".pga"))
 	source := urlFS(indexURL)
 
-	ok, err := copy(dest, source, indexName)
-	if !ok {
+	if err := updateCache(dest, source, indexName); err != nil {
```
Comment (bzz) [inline PublicGitArchive/pga/cmd/cache.go]: From the experience running a workshop with people new to src-d stack, one common pitfall I noticed (2 out of 10 new users) is that after running `pga` for the first time, users do not realize it's actually downloading an index, as there is no CLI feedback and it takes some time - and just perceive it as hang and do `Ctrl+C`.

On the next run, `pga list` does not work for them, as local index is corrupted.

Ofcourse having index md5 will catch that later in #57 , but while we are here, it could be easy to mitigate this type of failure by just printing some CLI output like "Index downloading in progress, please wait."

For sure, this could be done in subesequent PRs, but with the design proposed here `updateCache` already has debug logging built-in but it is used for both, index and .siva files download, while the CLI output is desired only for the index file.

Wondering what would be the best way to do that? Pass `isIndex` to `updateCache` and conditionally logrus.Info from there or is there a better way?

File: PublicGitArchive/pga/cmd/cache.go [hunk 4]
```diff
@@ -16,46 +15,68 @@ const (
 	indexName = "latest.csv.gz"
 )
 
-// copy checks whether a new version of the file in url exists and downloads it
-// to dest. It returns true when the file exists, and an error when it was not possible
-// to update it.
-func copy(dest, source FileSystem, name string) (bool, error) {
+// updateCache checks whether a new version of the file in url exists and downloads it
+// to dest. It returns an error when it was not possible to update it.
+func updateCache(dest, source FileSystem, name string) error {
```
Comment (bzz) [inline PublicGitArchive/pga/cmd/cache.go]: Is naming like `copyMaybe` a thing in Golang? Might come handy explaining this case

File: PublicGitArchive/pga/cmd/cache.go (hunk 1 above)
Comment (campoy) [reply PublicGitArchive/pga/cmd/cache.go]: We use the mod time only for file system types (or files) that do not support MD5 hashes.
The main goal is to abstract the behavior so we can add other file system backends easily later on.

File: PublicGitArchive/pga/cmd/cache.go (hunk 2 above)
Comment (campoy) [reply PublicGitArchive/pga/cmd/cache.go]: Good point.
I think it's fine to show that we're downloading stuff, specially for slow connections, since otherwise it might seem like the program is stuck without doing anything.

File: PublicGitArchive/pga/cmd/cache.go (hunk 3 above)
Comment (campoy) [reply PublicGitArchive/pga/cmd/cache.go]: Wait, that's exactly what the comment above does, right?
In case where the index is non existent or not up to date we warn that we're downloading a new version.

File: PublicGitArchive/pga/cmd/cache.go (hunk 4 above)
Comment (campoy) [reply PublicGitArchive/pga/cmd/cache.go]: `copyMaybe` doesn't sound idiomatic, I've never seen it before.
I think `updateCache` is pretty clear, but I'm happy to modify it if you think it's not.

**Comment by campoy** [comment]
Regarding the failure when the index is corrupt there's probably some work to improve the usability.
Could you file an issue specifically for that case?

Thanks for the thorough review!

File: PublicGitArchive/pga/cmd/cache.go (hunk 4 above)
Comment (bzz) [reply PublicGitArchive/pga/cmd/cache.go]: Up to you! It's just a common naming convention in many programming languages that origins from functional programming, to signify a function that have conditional side-effects.

See examples in: 
  - `maybe_download_iris_data` in [Tensorflow](https://github.com/tensorflow/tensorflow/blob/d4ad9c73969c45d1a224ebfc43eb645b9860216b/tensorflow/examples/learn/iris.py#L38) Python
 - `maybe_download_dbpedia` in [Tensorflow](https://github.com/tensorflow/tensorflow/blob/7f53659bc67bba5567ea3f0b69710329843e0228/tensorflow/contrib/learn/python/learn/datasets/produce_small_datasets.py#L32) Python
 - `resizeMeMaybe` in [Guava](https://github.com/google/guava/blob/7abf5990b29f19a7e8c458b63af73c88523e1820/android/guava/src/com/google/common/collect/ObjectCountHashMap.java#L326) Java

Quick search over stdlib shows some hits in both public and private APIs:
 - `maybeOpenNewConnections ` https://github.com/golang/go/blob/master/src/database/sql/sql.go#L980
 - `GetMaybeInsecure` https://github.com/golang/go/blob/178307c3a72a9da3d731fecf354630761d6b246c/src/cmd/go/internal/web/http.go#L76
